# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/walk_course_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '0613'

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # spring thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
